### ISSUE TITLE
cloudfoundry/cf-release #1038: traffic controller- dial error (read tcp i/o timeout)

### ISSUE THREAD

**Issue by vivekzhere** [cloudfoundry/cf-release#1093]
[Github Issue #1038](https://github.com/cloudfoundry/cf-release/issues/1038). 

I am also facing the same issue after updating my bosh lite setup to CF release v245. My system is also behind a proxy and the proxy variables are set properly. I had to rollback my setup to the older cf-release version to get logs working again. 

I am opening a new issue since i couldn't reopen the old issue. 

Feel free to reopen the old issue and close this so that discussion can be kept in one thread.

**Comment by dsabeti** [comment]
Hi @vivekzhere. Sorry for the delay.

Let's get some initial data out of the way. Could you provide the following information:

1. The version of CF you had before you updated to CF v245
2. Your deployment manifest with credentials redacted
3. A description of your proxy setup -- which environment variables are set, what their values correspond to (you don't have to publish sensitive information, but please explain their values, something like "the IP address of the router" or "the password for X")
4. Logs from the DEA, Doppler, and Traffic Controller after running `cf logs` or `cf push`.
5. The actual command line output from `cf logs` or `cf push`

Thanks,
David

**Comment by vivekzhere** [comment]
Hi @dsabeti . 

1. I was using CF v240 before the update.

2. I have deleted the CF v245 deployment and deployed v240 again. Now logs are again working. So I do not have the manifest for v245 anymore. I did not make any changes in the manifest. Just used the ./scripts/generate-bosh-lite-dev-manifest script.

3. Proxy variables are:
HTTPS_PROXY=http://proxy.hostname:8080
no_proxy=localhost,127.0.0.1,*.local,10.*,.xip.io,192.168.50.4,192.168.50.14,*.bosh-lite.com
https_proxy=http://proxy.hostname:8080
http_proxy=http://proxy.hostname:8080
HTTP_PROXY=http://proxy.hostname:8080

4,5. I do not have the v245 setup anymore. I can try deploying the latest cf-release version and check again.

**Comment by vivekzhere** [comment]
Hi @dsabeti 

I deployed the latest version (CF v246). Now the issue started again.

The manifest and output of following commands:
bosh logs ha_proxy_z1 0
bosh logs doppler_z1 0
bosh logs loggregator_trafficcontroller_z1 0

are attached [here cf.zip](https://github.com/cloudfoundry/cf-release/files/596553/cf.zip)

Output of cf logs

$ cf logs app
FAILED
Timed out waiting for connection to Loggregator (wss://doppler.bosh-lite.com:4443).

$cf logs app --recent
Connected, dumping recent logs for app vmaas-api in org testorg / space testspace as admin...

FAILED
unknown issue when making HTTP request to Loggregator

$

------------------------------------------------------------------

Using  CF_TRACE=true cf logs app
$ CF_TRACE=true cf logs app
.
.
.
WEBSOCKET REQUEST: [2016-11-17T09:31:09+05:30]
GET /apps/8a64bf66-0568-4dc2-a82a-93640c276829/stream HTTP/1.1
Host: wss://doppler.bosh-lite.com:4443
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: [HIDDEN]
Authorization: [PRIVATE DATA HIDDEN]
Origin: http://localhost


WEBSOCKET RESPONSE: [2016-11-17T09:31:14+05:30]
HTTP/1.1 500 Internal Server Error
Date: Thu, 17 Nov 2016 04:01:14 GMT
Content-Length: 21
Content-Type: text/plain; charset=utf-8


WEBSOCKET ERROR [2016-11-17T09:31:14+05:30]
Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.bosh-lite.com:4443).. Retrying...

WEBSOCKET REQUEST: [2016-11-17T09:31:15+05:30]
GET /apps/8a64bf66-0568-4dc2-a82a-93640c276829/stream HTTP/1.1
Host: wss://doppler.bosh-lite.com:4443
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: [HIDDEN]
Origin: http://localhost
Authorization: [PRIVATE DATA HIDDEN]

FAILED
Timed out waiting for connection to Loggregator (wss://doppler.bosh-lite.com:4443).

$

---------------------

**Comment by vivekzhere** [comment]
The output of cf push is : 

$ cf push
Using manifest file /home/vagrant/git/app/manifest.yml

Updating app app in org testorg / space testspace as admin...
OK

Using route app.bosh-lite.com
Uploading app...
Uploading app files from: /tmp/unzipped-app952141854
Uploading 1.1M, 182 files
Done uploading               
OK
Binding service vm-db-service to app app in org testorg / space testspace as admin...
OK

Stopping app app in org testorg / space testspace as admin...
OK

Warning: error tailing logs
Timed out waiting for connection to Loggregator (wss://doppler.bosh-lite.com:4443).
Starting app app in org testorg / space testspace as admin...

FAILED
Error restarting application: NoAppDetectedError
			
TIP: Buildpacks are detected when the "cf push" is executed from within the directory that contains the app source code.

Use 'cf buildpacks' to see a list of supported buildpacks.

Use 'cf logs app --recent' for more in depth log information.

$
---------------------------------------------------------------
I tried pushing again. This time it succeeded and the logs started working.

------------------------------------------------------------------------

$ cf push                            
Using manifest file /home/vagrant/git/vmaas/virtual-machines-api/manifest.yml

Updating app app in org testorg / space testspace as admin...
OK

Using route app.bosh-lite.com
Uploading app...
Uploading app files from: /tmp/unzipped-app272360874
Uploading 1.1M, 182 files
Done uploading               
OK
Binding service vm-db-service to app app in org testorg / space testspace as admin...
OK

Starting app app in org testorg / space testspace as admin...
-----> Downloaded app package (40M)
-----> Downloaded app buildpack cache (46M)
-----> Java Buildpack Version: v3.10 | https://github.com/cloudfoundry/java-buildpack.git#193d6b7
-----> Downloading Open Jdk JRE 1.8.0_111 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_111.tar.gz (1m 45s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.7s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xmx317161K -XX:MaxMetaspaceSize=64M -Xss228K -Xms317161K -XX:MetaspaceSize=64M
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)

-----> Uploading droplet (85M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App app was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k.. -memoryWeights=heap:65,metaspace:10,native:15,stack:10 -memoryInitials=heap:100%,metaspace:100% -stackThreads=300 -totMemory=$MEMORY_LIMIT) && JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`

Showing health and status for app app in org testorg / space testspace as admin...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: app.bosh-lite.com
last uploaded: Thu Nov 17 04:37:20 UTC 2016
stack: cflinuxfs2
buildpack: java-buildpack=v3.10-https://github.com/cloudfoundry/java-buildpack.git#193d6b7 java-main open-jdk-like-jre=1.8.0_111 open-jdk-like-memory-calculator=2.0.2_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu      memory           disk      details
#0   running   2016-11-17 10:10:49 AM   254.0%   441.3M of 512M   0 of 1G




$ cf logs app        
Connected, tailing logs for app app in org testorg / space testspace as admin...

2016-11-17T10:37:47.32+0530 [App/0]      OUT 2016-11-17 05:07:47.321  INFO 29 --- [io-61001-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-11-17T10:37:47.32+0530 [App/0]      OUT 2016-11-17 05:07:47.322  INFO 29 --- [io-61001-exec-2] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2016-11-17T10:37:47.37+0530 [App/0]      OUT 2016-11-17 05:07:47.375  INFO 29 --- [io-61001-exec-2] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 53 ms
2016-11-17T10:37:48.16+0530 [RTR/0]      OUT app.bosh-lite.com - [17/11/2016:05:07:47.228 +0000] "GET /v2/catalog HTTP/1.1" 200 0 1235 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" 10.244.0.34:48818 10.244.0.26:61001 x_forwarded_for:"192.168.50.14, 10.244.0.34" x_forwarded_proto:"http" vcap_request_id:652936b2-dc5b-4560-482b-8df2bf057ede response_time:0.933964044 app_id:8a64bf66-0568-4dc2-a82a-93640c276829 app_index:-

**Comment by jaresty** [comment]
@vivekzhere Are you still having a problem?  I'm not sure I understand the issue.  Can you please summarize, step-by-step, the issue you are having?

**Comment by JesseTAlford** [comment]
@vivekzhere, could you please confirm you're still seeing an issue? We plan to close this issue in two days unless we hear you're still affected.

**Comment by vivekzhere** [comment]
@jaresty @JesseTAlford I was facing the issue with cf-release versions v245, v246 and v247. With v246 the issue was intermittent. Now I am using v240 with an older version of cf-cli(6.18.1) and now I am able see the logs. I had to downgrade to v240 because logs were not working in in higher versions.

Summary of the issue:
I have my bosh-lite setup behind a network proxy. I have set the proxy and no_proxy variables in the Vagrantfile using vagrant-proxyconf. I deployed cf-release version v245 / v246 / v247. After that 

```
$ cf logs app
FAILED
Timed out waiting for connection to Loggregator (wss://doppler.bosh-lite.com:4443).

$cf logs app --recent
Connected, dumping recent logs for app vmaas-api in org testorg / space testspace as admin...

FAILED
unknown issue when making HTTP request to Loggregator

$
```

cf push gives the following warning:

```
Warning: error tailing logs
Timed out waiting for connection to Loggregator (wss://doppler.bosh-lite.com:4443).
```

I tried out different versions of cf-cli including the latest one. But the issue was still there. Then i deleted the deployment and deployed cf-release v240 and installed cf-cli(6.18.1). Then the logs started working again.

Initially my setup was this and the whole issue started when i tried to update to cf-release v245.

**Comment by ChunyiLyu** [comment]
We've come to suspect that the port numbers for handling websocket connections may not be getting properly passed along and respected.

If that's the issue, using the latest cf-release along with the latest cf cli _should_ fix this issue, these days. You could try that, but I understand it's not necessarily a cheap experiment.

To help us diagnose, could you please give us the output from `cf curl v2/info`?

**Comment by dsabeti** [comment]
@vivekzhere. I'm going to close this issue due to inactivity. Feel free to re-open the it if you still need help.
