### ISSUE TITLE
Update fog to 1.27.0 and pass through aws_signature_version fog connection option

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry/cf-release#613]
As per title, please update fog in the release to 1.27.0 and pass through the aws_signature_version connection option into fog

This resolves an issue with fog and certain S3-compatible object stores (namely Atmos). 1.25.0 upgrades to signature version v4 from v2 in 1.23.0 but does not allow an over-ride. 1.27.0 adds the aws_signature_version connection option to fall back to v2

This currently prevents Atmos S3-interface being used as a blobstore

**Comment by scotttag** [comment]
Sorry, minor correction, 1.26.0 is the fog version this is fixed in - but 1.27.0 is latest which also has the fix of course

**Comment by luan** [comment]
@scotttag,

We update the fog gem to 1.27.0, it will be released with cf-release v198. As far as the property goes, we treat it as an opaque hash, so you can pass in any arbitrary arguments fog may want (such as the `aws_signature_version ` you mentioned).

Thanks,
@luan & @DanLavine, CF Runtime Team

**Comment by scotttag** [comment]
Great, thanks for the rapid response, I'll get on and test v198!

**Comment by ramonskie** [comment]
this still not works
its related to this commit
https://github.com/cloudfoundry/cloud_controller_ng/commit/b76e32e9e62f2e0cb3d59a2cc62cde50e5483175

see https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/5W_5aAvZRHc
